version: '3'
services:
  azure-storage:
    image: azure-storage
    build:
      context: ./azure-storage
      dockerfile: Dockerfile
    container_name: video-storage
    ports:
      - '4000:80'
    environment:
      - PORT=80
      - STORAGE_ACCOUNT_NAME=20djoa9
      - STORAGE_ACCESS_KEY=QG9+uomGuWE4FUV9DC12xluU2rNXnItSK7YzdVPU1NtC56D6jRIp+kzT9Rg4G30JKMMteui2+jYk69QSrPnbmw==
    restart: 'no'
  video-streaming:
    image: video-streaming
    build:
      context: ./video-streaming
      dockerfile: Dockerfile
    container_name: video-streaming
    ports:
      - '4001:80'
    environment:
      - PORT=80
      - VIDEO_STORAGE_HOST=video-storage
      - VIDEO_STORAGE_PORT=80
    restart: 'no'
