version: '3'
services:
  history:
    image: history
    build:
      context: ./history
      dockerfile: Dockerfile-dev
    container_name: history
    volumes:
      - /tmp/history/npm-cache:/root/.npm:z
      - ./history/src:/usr/src/app/src/:z
    ports:
      - '4002:80'
    environment:
      - PORT=80
      - NODE_ENV=development
    restart: 'no'
  db:
    image: mongo:4.2.8
    container_name: db
    ports:
      - '27017:27017' # For interactions w/ local machine
    restart: always
  video-streaming:
    image: video-streaming
    build:
      context: ./video-streaming
      dockerfile: Dockerfile
    container_name: video-streaming
    ports:
      - '4000:80'
    environment:
      - PORT=80
      - DB_HOST=mongodb://db:27017
      - DB_NAME=video-streaming
      - VIDEO_STORAGE_HOST=video-storage
      - VIDEO_STORAGE_PORT=80
    restart: 'no'
  azure-storage:
    image: azure-storage
    build:
      context: ./azure-storage
      dockerfile: Dockerfile
    container_name: video-storage
    ports:
      - '4001:80'
    environment:
      - PORT=80
      - STORAGE_ACCOUNT_NAME=20djoa9
      - STORAGE_ACCESS_KEY=QG9+uomGuWE4FUV9DC12xluU2rNXnItSK7YzdVPU1NtC56D6jRIp+kzT9Rg4G30JKMMteui2+jYk69QSrPnbmw==
    restart: 'no'
